version: '3.8'

services:
  app:
    build: .
    container_name: exchanger_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
